# Generated by Django 5.2.7 on 2025-10-14 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('location', models.CharField(max_length=200, verbose_name='Location/Area')),
                ('address', models.TextField(help_text='Your complete address', verbose_name='Place Where You Stay')),
                ('service', models.CharField(choices=[('gym_registration', 'Gym Registration - GHC 450'), ('full_body_massage', 'Full Body Massage - GHC 350 (In-House)'), ('neck_shoulder_pain', 'Neck & Shoulder Pain - GHC 250'), ('reflexo_therapy', 'Reflexo Therapy - GHC 250'), ('lower_back_shoulder', 'Lower Back & Shoulder - GHC 300'), ('deep_tissue_massage', 'Deep Tissue Massage - GHC 400 (In-House)'), ('home_full_body_massage', 'Full Body Massage - GHC 450 (Home Service)'), ('home_neck_shoulder', 'Neck & Shoulder Pain - GHC 350 (Home Service)'), ('home_reflexo', 'Reflexo Therapy - GHC 350 (Home Service)'), ('home_lower_back', 'Lower Back & Shoulder - GHC 400 (Home Service)'), ('home_deep_tissue', 'Deep Tissue Massage - GHC 500 (Home Service)'), ('driving_fatigue', 'Driving Fatigue - GHC 500 (Home Service)')], max_length=50, verbose_name='Service Requested')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Additional Notes (Optional)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user account if logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
